name = "juno-beaker-test"

gas_price = '0.025ucosm'
gas_adjustment = 1.3
account_prefix = 'juno'
derivation_path = '''m/44'/118'/0'/0/0'''

[networks.local]
chain_id = 'testing'
network_variant = 'Local'
grpc_endpoint = 'http://localhost:9090'
rpc_endpoint = 'http://localhost:26657'

[accounts.junotest]
mnemonic = "clip hire initial neck maid actor venue client foam budget lock catalog sweet steak waste crater broccoli pipe steak sister coyote moment obvious choose"